version: '3.8'

services:

  db:
    image: postgres:15.1-alpine
    volumes:
      - task_planner_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -d postgres
      timeout: 3s
      interval: 5s
      retries: 10

  api:
    build: .
#    env_file: .env
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./core:/opt/core
      - ./todolist:/opt/todolist
      - django_static:/opt/static/

#  migrations:
#    build:
#      context: .
#    env_file:
#      - .env
#    command: >
#      sh -c 'python manage.py migrate'
#    depends_on:
#      db:
#        condition: service_healthy

#  migrations:
#    build:
#      context: .
#    depends_on:
#      postgres:
#        condition: service_healthy
#    command: python manage.py migrate

  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static


volumes:
  task_planner_data:
  django_static: