version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - task_planner_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      timeout: 3s
      interval: 5s
      retries: 10

volumes:
  task_planner_data:
