# Generated by Django 4.0.1 on 2023-05-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'],
                     'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
